
version: 2

models:
  - name: dim_zones
    description: ""
    columns:
      - name: locationid
        data_type: int64
        description: ""

      - name: borough
        data_type: string
        description: ""

      - name: zone
        data_type: string
        description: ""

      - name: service_zone
        data_type: string
        description: ""